nodeLinker: node-modules
defaultSemverRangePrefix: ""
npmRegistryServer: "https://registry.npmjs.org"
npmAuditRegistry: "https://registry.npmjs.org"
npmMinimalAgeGate: "14d"
enableHardenedMode: true
enableScripts: true
